### ISSUE TITLE
Error on "perl Makefile.PL"

### ISSUE THREAD

**Issue by royobrecht** [michelgokan/collectd-top#1]
Please see the following errors:
_________________________________

$perl Makefile.PL 
Checking if your kit is complete...
Warning: the following files are missing in your kit:
	README
Please inform the author.
WARNING: Setting VERSION via file 'lib/Collectd/Plugins/Top.pm' failed
 at /usr/share/perl/5.22/ExtUtils/MakeMaker.pm line 651.
WARNING: Setting ABSTRACT via file 'lib/Collectd/Plugins/Top.pm' failed
 at /usr/share/perl/5.22/ExtUtils/MakeMaker.pm line 663.
Generating a Unix-style Makefile
Writing Makefile for Collectd::Plugins::Top
Writing MYMETA.yml and MYMETA.json

NOTE: 
perl --version

This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi
(with 69 registered patches, see perl -V for more detail)

**Comment by rajeshbabukolli** [comment]
I am also facing same issue.

**Comment by michelgokan** [comment]
@rajeshbabukolli @royobrecht Fixed the issue.

**Comment by rajeshbabukolli** [comment]
Make test failed, this is my output

#make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/Collectd-Plugins-Top.t .. 1/1
#   Failed test 'use Collectd::Plugins::Top;'
#   at t/Collectd-Plugins-Top.t line 12.
#     Tried to use 'Collectd::Plugins::Top'.
#     Error:  Bareword "LOG_ERR" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 165.
# Bareword "TYPE_CONFIG" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 119.
# Bareword "TYPE_INIT" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 119.
# Bareword "TYPE_READ" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 119.
# Bareword "TYPE_WRITE" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 119.
# Bareword "TYPE_SHUTDOWN" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 119.
# Bareword "TYPE_LOG" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 119.
# Bareword "TYPE_NOTIF" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 119.
# Bareword "TYPE_FLUSH" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 119.
# Bareword "FC_MATCH" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 130.
# Bareword "FC_TARGET" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 130.
# Bareword "FC_MATCH" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 135.
# Bareword "FC_TARGET" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 135.
# Bareword "FC_CB_EXEC" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 140.
# Bareword "FC_CB_CREATE" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 140.
# Bareword "FC_CB_DESTROY" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 140.
# Compilation failed in require at /../../../collectd/top-plugin/collectd-top/blib/lib/Collectd/Plugins/Top.pm line 6.
# BEGIN failed--compilation aborted at /../../../collectd/top-plugin/collectd-top/blib/lib/Collectd/Plugins/Top.pm line 6.
# Compilation failed in require at t/Collectd-Plugins-Top.t line 12.
# BEGIN failed--compilation aborted at t/Collectd-Plugins-Top.t line 12.
# Looks like you failed 1 test of 1.
t/Collectd-Plugins-Top.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
t/Collectd-top.t .......... Array found where operator expected at t/Collectd-top.t line 12, at end of line
        (Do you need to predeclare top?)
t/Collectd-top.t .......... 1/1
#   Failed test 'use Collectd-top;'
#   at t/Collectd-top.t line 12.
#     Tried to use 'Collectd-top'.
#     Error:  syntax error at t/Collectd-top.t line 12, near "top @"
# Looks like you failed 1 test of 1.
t/Collectd-top.t .......... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests

Test Summary Report
-------------------
t/Collectd-Plugins-Top.t (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
t/Collectd-top.t        (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=2, Tests=2,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.03 cusr  0.00 csys =  0.06 CPU)
Result: FAIL
Failed 2/2 test programs. 2/2 subtests failed.
Makefile:805: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 1
