### ISSUE TITLE
Make test failed

### ISSUE THREAD

**Issue by rajeshbabukolli** [michelgokan/collectd-top#3]
make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/Collectd-Plugins-Top.t .. 1/1
#  Failed test 'use Collectd::Plugins::Top;'
#   at t/Collectd-Plugins-Top.t line 12.
#     Tried to use 'Collectd::Plugins::Top'.
#     Error:  Bareword "LOG_ERR" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 165.
# Bareword "TYPE_CONFIG" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 119.
# Bareword "TYPE_INIT" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 119.
# Bareword "TYPE_READ" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 119.
# Bareword "TYPE_WRITE" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 119.
# Bareword "TYPE_SHUTDOWN" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 119.
# Bareword "TYPE_LOG" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 119.
# Bareword "TYPE_NOTIF" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 119.
# Bareword "TYPE_FLUSH" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 119.
# Bareword "FC_MATCH" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 130.
# Bareword "FC_TARGET" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 130.
# Bareword "FC_MATCH" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 135.
# Bareword "FC_TARGET" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 135.
# Bareword "FC_CB_EXEC" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 140.
# Bareword "FC_CB_CREATE" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 140.
# Bareword "FC_CB_DESTROY" not allowed while "strict subs" in use at /usr/share/perl5/Collectd.pm line 140.
# Compilation failed in require at /../../../collectd/top-plugin/collectd-top/blib/lib/Collectd/Plugins/Top.pm line 6.
# BEGIN failed--compilation aborted at /../../../collectd/top-plugin/collectd-top/blib/lib/Collectd/Plugins/Top.pm line 6.
# Compilation failed in require at t/Collectd-Plugins-Top.t line 12.
# BEGIN failed--compilation aborted at t/Collectd-Plugins-Top.t line 12.
# Looks like you failed 1 test of 1.
t/Collectd-Plugins-Top.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
t/Collectd-top.t .......... Array found where operator expected at t/Collectd-top.t line 12, at end of line
        (Do you need to predeclare top?)
t/Collectd-top.t .......... 1/1
#   Failed test 'use Collectd-top;'
#   at t/Collectd-top.t line 12.
#     Tried to use 'Collectd-top'.
#     Error:  syntax error at t/Collectd-top.t line 12, near "top @"
# Looks like you failed 1 test of 1.
t/Collectd-top.t .......... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests

Test Summary Report
-------------------
t/Collectd-Plugins-Top.t (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
t/Collectd-top.t        (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=2, Tests=2,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.03 cusr  0.00 csys =  0.06 CPU)
Result: FAIL
Failed 2/2 test programs. 2/2 subtests failed.
Makefile:805: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 1

**Comment by michelgokan** [comment]
@rajeshbabukolli  It should be fixed now!

**Comment by rajeshbabukolli** [comment]
Yes, it installed with any errors, but top plugin is not displayed in collectd-web.
For that, i found the issue, i.e, here plugin name "Top" should be case sensitive.
1. <Plugin perl>
2.         BaseName "Collectd::Plugins"
3.         LoadPlugin "Top"
4.        <Plugin "top">
5.               TopProcessesCountByMemory "4"
6.                TopProcessesCountByCPU "5"
7.        </Plugin>
8. </Plugin>

Line 4: --> plugin name should be "Top" not "top".

Then it worked for me.

But it is showing, so many graphs, could you consolidate as default 3 for cpu & 3 for memory.

**Comment by michelgokan** [comment]
@rajeshbabukolli The default for both is already 3. In your configs, you set TopProcessesCountByMemory to 4 and TopProcessesCountByCPU to 5. You can change them and restart collectd. For the case sensitivity, I'm not sure as it works fine in the test environment. I will check once more.

**Comment by rajeshbabukolli** [comment]
Thank you Michel
